const builtinIcons = [
  {
    id: "github",
    name: "GitHub",
    url: "https://github.com",
    iconType: "logo",
    iconLogo: "https://github.com/favicon.ico",
  },
  {
    id: "google",
    name: "Google",
    url: "https://www.google.com",
    iconType: "logo",
    iconLogo: "https://www.google.com/favicon.ico",
  },
  {
    id: "youtube",
    name: "YouTube",
    url: "https://www.youtube.com",
    iconType: "logo",
    iconLogo: "https://www.youtube.com/favicon.ico",
  },
  {
    id: "twitter",
    name: "X",
    url: "https://x.com",
    iconType: "logo",
    iconLogo: "https://x.com/favicon.ico",
  },
  {
    id: "reddit",
    name: "Reddit",
    url: "https://www.reddit.com",
    iconType: "logo",
    iconLogo: "https://www.reddit.com/favicon.ico",
  },
  {
    id: "stackoverflow",
    name: "Stack Overflow",
    url: "https://stackoverflow.com",
    iconType: "logo",
    iconLogo: "https://stackoverflow.com/favicon.ico",
  },
  {
    id: "mdn",
    name: "MDN",
    url: "https://developer.mozilla.org",
    iconType: "logo",
    iconLogo: "https://developer.mozilla.org/favicon.ico",
  },
  {
    id: "wikipedia",
    name: "Wikipedia",
    url: "https://www.wikipedia.org",
    iconType: "logo",
    iconLogo: "https://www.wikipedia.org/favicon.ico",
  },
  {
    id: "amazon",
    name: "Amazon",
    url: "https://www.amazon.com",
    iconType: "logo",
    iconLogo: "https://www.amazon.com/favicon.ico",
  },
  {
    id: "netflix",
    name: "Netflix",
    url: "https://www.netflix.com",
    iconType: "logo",
    iconLogo: "https://www.netflix.com/favicon.ico",
  },
  {
    id: "spotify",
    name: "Spotify",
    url: "https://www.spotify.com",
    iconType: "logo",
    iconLogo: "https://www.spotify.com/favicon.ico",
  },
  {
    id: "discord",
    name: "Discord",
    url: "https://discord.com",
    iconType: "logo",
    iconLogo: "https://discord.com/favicon.ico",
  },
  {
    id: "twitch",
    name: "Twitch",
    url: "https://www.twitch.tv",
    iconType: "logo",
    iconLogo: "https://www.twitch.tv/favicon.ico",
  },
  {
    id: "linkedin",
    name: "LinkedIn",
    url: "https://www.linkedin.com",
    iconType: "logo",
    iconLogo: "https://www.linkedin.com/favicon.ico",
  },
  {
    id: "instagram",
    name: "Instagram",
    url: "https://www.instagram.com",
    iconType: "logo",
    iconLogo: "https://www.instagram.com/favicon.ico",
  },
  {
    id: "facebook",
    name: "Facebook",
    url: "https://www.facebook.com",
    iconType: "logo",
    iconLogo: "https://www.facebook.com/favicon.ico",
  },
  {
    id: "tiktok",
    name: "TikTok",
    url: "https://www.tiktok.com",
    iconType: "logo",
    iconLogo: "https://www.tiktok.com/favicon.ico",
  },
  {
    id: "bilibili",
    name: "Bilibili",
    url: "https://www.bilibili.com",
    iconType: "logo",
    iconLogo: "https://www.bilibili.com/favicon.ico",
  },
  {
    id: "zhihu",
    name: "Zhihu",
    url: "https://www.zhihu.com",
    iconType: "logo",
    iconLogo: "https://www.zhihu.com/favicon.ico",
  },
  {
    id: "weibo",
    name: "Weibo",
    url: "https://weibo.com",
    iconType: "logo",
    iconLogo: "https://weibo.com/favicon.ico",
  },
  {
    id: "taobao",
    name: "Taobao",
    url: "https://www.taobao.com",
    iconType: "logo",
    iconLogo: "https://www.taobao.com/favicon.ico",
  },
  {
    id: "jd",
    name: "JD",
    url: "https://www.jd.com",
    iconType: "logo",
    iconLogo: "https://www.jd.com/favicon.ico",
  },
  {
    id: "baidu",
    name: "Baidu",
    url: "https://www.baidu.com",
    iconType: "logo",
    iconLogo: "https://www.baidu.com/favicon.ico",
  },
  {
    id: "douban",
    name: "Douban",
    url: "https://www.douban.com",
    iconType: "logo",
    iconLogo: "https://www.douban.com/favicon.ico",
  },
  {
    id: "dribbble",
    name: "Dribbble",
    url: "https://dribbble.com",
    iconType: "logo",
    iconLogo: "https://dribbble.com/favicon.ico",
  },
  {
    id: "behance",
    name: "Behance",
    url: "https://www.behance.net",
    iconType: "logo",
    iconLogo: "https://www.behance.net/favicon.ico",
  },
  {
    id: "medium",
    name: "Medium",
    url: "https://medium.com",
    iconType: "logo",
    iconLogo: "https://medium.com/favicon.ico",
  },
  {
    id: "devto",
    name: "Dev.to",
    url: "https://dev.to",
    iconType: "logo",
    iconLogo: "https://dev.to/favicon.ico",
  },
  {
    id: "producthunt",
    name: "Product Hunt",
    url: "https://www.producthunt.com",
    iconType: "logo",
    iconLogo: "https://www.producthunt.com/favicon.ico",
  },
];

export default builtinIcons;
